name: CD

on: 
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    # - name: Release
    #   run: yarn release --prerelease alpha

    # - name: Publish
    #   run: npm publish --access public
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
