name: CD

on: 
  push:
    branches:
    - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: GitHub User
      run: |
        git config --global user.email "ivanildo.decastro085@gmail.com"
        git config --global user.name "Ivanildo de Castro"

    - uses: actions/setup-node@v2
      with:
        node-version: "14"
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
    
    - name: Coverage
      run: yarn coverage

    - name: Codecov
      uses: codecov/codecov-action@v1
    
    - name: Build
      run: yarn build

    - name: Release
      run: |
        yarn release --prerelease alpha
        git push --follow-tags origin main

    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
