name: CI

on:
  push:
    paths:
    - "**.js"
    - "**.jsx"
    - "**.ts"
    - "**.tsx"

    branches:
    - "feature/**"

jobs:
  feature:
    name: Feature
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
